# OWL需求分析助手配置文件

# 系统配置
system:
  name: "OWL需求分析助手"
  version: "0.1.0"
  description: "基于多智能体的需求分析系统"
  mode: web  # 运行模式：web, cli, once
  port: 8082  # Web服务端口
  host: "0.0.0.0"  # Web服务主机
  log_level: INFO
  log_file: "logs/app.log"

# LLM配置
llm:
  provider: ollama  # LLM提供商
  model: mistral  # 模型名称
  api_key: ""  # 从环境变量获取
  temperature: 0.7
  max_tokens: 2000
  timeout: 60

# Web服务器配置
web:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_origins: ["*"]
  static_dir: "static"
  templates_dir: "templates"
  static_path: "static"
  templates_path: "templates"
  session_timeout: 3600  # 会话超时时间（秒）
  max_connections: 100  # 最大并发连接数

# 智能体配置
agents:
  requirements_extractor:
    name: "需求提取智能体"
    role: "extractor"
    description: "负责从用户输入中提取关键需求"
    prompt_template: |
      你是一个专业的需求分析师，负责从用户输入中提取关键需求。
      请仔细分析以下输入，提取出所有明确和隐含的需求：
      
      {input_text}
      
      请以结构化的方式输出需求列表，包括：
      1. 功能需求
      2. 非功能需求
      3. 约束条件
      4. 优先级
      5. 依赖关系
  requirements_analyzer:
    name: "需求分析智能体"
    role: "analyzer"
    description: "负责深入分析需求的可行性和影响"
    prompt_template: |
      作为需求分析专家，请对以下需求进行深入分析：
      
      {requirements}
      
      请提供以下分析：
      1. 技术可行性评估
      2. 资源需求评估
      3. 风险分析
      4. 实现复杂度评估
      5. 建议的技术方案
  quality_checker:
    name: "质量检查智能体"
    role: "checker"
    description: "负责检查需求的质量和完整性"
    prompt_template: |
      作为质量保证专家，请检查以下需求的质量：
      
      {requirements}
      
      请评估以下方面：
      1. 需求的完整性
      2. 需求的清晰度
      3. 需求的一致性
      4. 需求的可测试性
      5. 需求的可追踪性
    enabled: true
    threshold: 0.8
  documentation_generator:
    name: "文档生成智能体"
    role: "generator"
    description: "负责生成标准化的需求文档"
    prompt_template: |
      作为技术文档专家，请根据以下分析结果生成标准化的需求文档：
      
      {analysis_results}
      
      请生成包含以下部分的文档：
      1. 项目概述
      2. 需求清单
      3. 技术方案
      4. 实现计划
      5. 风险管理
    enabled: true
    format: markdown

# System Configuration
templates:
  directory: "templates/prompts"
output_dir: "output"
template_dir: "templates"
workspace_dir: "workspace"

# Web Server Configuration
web_host: "127.0.0.1"
web_port: 8080
