site_name: OWL Requirements Analysis Assistant
site_description: Documentation for the OWL Requirements Analysis Assistant
site_author: OWL Framework Team
repo_url: https://github.com/your-org/owl
repo_name: your-org/owl
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Web Interface: user-guide/web-interface.md
    - CLI Interface: user-guide/cli-interface.md
    - Single Request Mode: user-guide/single-request.md
  - Architecture:
    - Overview: architecture/overview.md
    - Multi-agent System: architecture/multi-agent.md
    - Components: architecture/components.md
  - API Reference:
    - Core API: api/core.md
    - Web API: api/web.md
    - CLI API: api/cli.md
  - Development:
    - Contributing: development/contributing.md
    - Development Setup: development/setup.md
    - Testing: development/testing.md
  - About:
    - License: about/license.md
    - Changelog: about/changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/owl
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/owl-requirements-analysis/

extra_css:
  - stylesheets/extra.css 